### ISSUE TITLE
QT Cluster - Read values / update UI accordingly

### ISSUE THREAD

**Issue by peterbikes** [SEAME-pt/JetPackJoyRide#35]
- [x] Speedometer - keyboard input
- [x] Arrow Widget - via keyboard inputs
- [x] Turn Signals - via keyboard inputs
- [x] CPU temperature - via linux command
- [x] Battery level - via linux command
